[package]
name = "bevy_snake"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
rand = "0.8"

# Enable some optimizations in debug mode
[profile.dev]
opt-level = 1

# Dependencies will still be optimized even in debug mode
[profile.dev.package."*"]
opt-level = 3
